#day 7

library(patchwork)
library(ggrain)
library(usmap)

#nps econ data

cali <- nps_econ_data |> 
  filter(state %in% c("CA", "NM", "CO","AZ","UT","OR","WA", "ID","NV","WY","MT")) |> 
  distinct(econ_output, .keep_all = TRUE)

western <- ggplot(data = cali, 
       aes(x = state, y = econ_output, fill = state)) +
  geom_rain(alpha = 0.5) +
  theme_bw() +
  labs(x = "State",y = "Economic Output ($000)",subtitle = "For Western States") +
  theme(legend.position = "none") +
  ylim(15, 3000000) 

total_output <- nps_econ_data |> 
  mutate(total = rep("Total",489)) |> 
  distinct(econ_output, .keep_all = TRUE)

all_us <- ggplot(data = total_output, aes(x = total, y = econ_output)) +
  geom_rain(alpha = 0.5) +
  theme_bw() +
  labs(x = "", y = "Economic Output ($000)", subtitle = "All U.S.") +
  ylim(15, 3000000) 
  
ca_out <- nps_econ_data |> 
  filter(state == "CA") |> 
  distinct(econ_output, .keep_all = TRUE) |> 
  mutate(total = "California")

ca_plot <- ggplot(data = ca_out, aes(x = total, y = econ_output)) +
  geom_rain(alpha = 0.5) +
  theme_bw() +
  labs(x = "", y = "Economic Output ($000)", subtitle = "California")

state <- us_map(regions = "states")

state_sum <- nps_econ_data |> 
  group_by(state) |> 
  summarize(tot_state = sum(econ_output)) |> 
  rename(abbr = state)

map_data <- state |> 
  left_join(state_sum) |> 
  filter(full != ("Puerto Rico"))

nps_map <- ggplot(map_data) +
  geom_sf(aes(fill = tot_state)) +
  theme_bw() +
  labs(fill = "Economic Output \n($000)")

(all_us + ca_plot) +
  plot_annotation(
    title = "Economic output generated by NPS visits in 2024 across the U.S.",
    caption = "Data from NPS Visitor Report"
  )

nps_map

